### ISSUE TITLE
Aleph RESTful API driver

### ISSUE THREAD

**Issue by black23** [open-source-knihovna/tohu#45]
Documentation & description:
https://developers.exlibrisgroup.com/aleph/apis/Aleph-RESTful-APIs

**Comment by black23** [comment]
functions:

- [ ] Acquisition Requests Info
- [ ] Address
- [ ] Cancel Hold
- [ ] Cash
- [ ] Circulation Actions
- [ ] Get Patron Information
- [ ] Get Patron Status
- [ ] Get Records
- [ ] Items per Patron
- [ ] Loans
- [ ] New Patron
- [ ] Password
- [ ] Patron Blocks
- [ ] Patron Registration
- [ ] Renew Loan

Please add requested functions into comments.

**Comment by black23** [comment]
Adept to depricated?

**Comment by xmorave2** [comment]
Yes, this probably will never happen
